//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZincirMarketProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magazalar
    {

        public int MagazaId { get; set; }
        public string Sehir { get; set; }
        public string Telefon { get; set; }
        public string Ulke { get; set; }
        public int AracPlaka { get; set; }
    }
}
