//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZincirMarketProje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarketlerimContainer : DbContext
    {
        public MarketlerimContainer()
            : base("name=MarketlerimContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Personeller> PersonellerSet { get; set; }
        public virtual DbSet<Magazalar> MagazalarSet { get; set; }
        public virtual DbSet<Sevkiyat> SevkiyatSet { get; set; }
        public virtual DbSet<Depolar> DepolarSet { get; set; }
        public virtual DbSet<Urünler> UrünlerSet { get; set; }
        public virtual DbSet<Müsteri> MüsteriSet { get; set; }
    }
}
