//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZincirMarketProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Müsteri
    {
        public int müsteriId { get; set; }
        public string AdSoyad { get; set; }
        public string Telefon { get; set; }
        public string Sehir { get; set; }
    }
}
