//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZincirMarketProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sevkiyat
    {
        public int AracPlaka { get; set; }
        public string SürücüAdSoyad { get; set; }
        public string Telefon { get; set; }
        public int Maas { get; set; }
        public string Vardiya { get; set; }
        public int DepoId { get; set; }
    }
}
