//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZincirMarketProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urünler
    {
        public int ürünId { get; set; }
        public string ürünCinsi { get; set; }
        public int ürünFiyati { get; set; }
        public int müsteriId { get; set; }
    }
}
